### ISSUE TITLE
ImportError: No module named skimage.io

### ISSUE THREAD

**Issue by fengjinhai** [yahoo/open_nsfw#13]
hi, I install docker and Build a caffe docker image sucessfully,
but is run the programm, it report the error.
please help me.

root@iZ25q8sqgi7Z:~/open_nsfw# docker run caffe:cpu caffe --version
libdc1394 error: Failed to initialize libdc1394
caffe version 1.0.0-rc3

root@iZ25q8sqgi7Z:~/open_nsfw# docker run --volume=$(pwd):/workspace caffe:cpu \
> python ./classify_nsfw.py \
> --model_def nsfw_model/deploy.prototxt \
> --pretrained_model nsfw_model/resnet_50_1by2_nsfw.caffemodel \
> test_image.jpg
libdc1394 error: Failed to initialize libdc1394
Traceback (most recent call last):
  File "./classify_nsfw.py", line 16, in <module>
    import caffe
  File "/opt/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/opt/caffe/python/caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "/opt/caffe/python/caffe/io.py", line 2, in <module>
    import skimage.io
ImportError: No module named skimage.io

**Comment by sdvdxl** [comment]
run command `pip install scikit-image`

**Comment by JeffreyYafeiHu** [comment]
I used apt-get install and solved my problem. Run the following commands,

sudo apt-get install python-matplotlib python-numpy python-pil python-scipy

sudo apt-get install build-essential cython

sudo apt-get install python-skimage

**Comment by Ashutosh1995** [comment]
Thanks a lot @JeffreyYafeiHu , it worked :-)

**Comment by Jeonguuz** [comment]
Thank you @JeffreyYafeiHu. it helped

**Comment by bjce** [comment]
Hello 

I also have problem. When I run this command

```
from skimage import io
io.use_plugin("pil", "imread")
img = io.imread("/Users/mymac/Downloads/image.png")
io.use_plugin("qt", "imshow")
io.imshow(img,fancy=True)
io.show()
```

I get the following error message: 

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-24-8355b47d9c39> in <module>()
----> 1 io.use_plugin("qt", "imshow")
      2 io.imshow(img,fancy=True)
      3 io.show()

/anaconda3/lib/python3.6/site-packages/skimage/io/manage_plugins.py in use_plugin(name, kind)

/anaconda3/lib/python3.6/site-packages/skimage/io/manage_plugins.py in _load(plugin)

ModuleNotFoundError: No module named 'skimage.io._plugins.qt_plugin'
```

**Comment by sheddup** [comment]
I'm new to docker where do I install scikit-image? I've run it inside the container, I've run it on the host I've run it everywhere I know how to run it yet I still get an ImportError this is so frustrating I feel like this happens every time I try to use Linux.

**Comment by qianjun1987** [comment]
> hi, I install docker and Build a caffe docker image sucessfully,
> but is run the programm, it report the error.
> please help me.
> 
> root@iZ25q8sqgi7Z:~/open_nsfw# docker run caffe:cpu caffe --version
> libdc1394 error: Failed to initialize libdc1394
> caffe version 1.0.0-rc3
> 
> root@iZ25q8sqgi7Z:~/open_nsfw# docker run --volume=$(pwd):/workspace caffe:cpu \
> 
> > python ./classify_nsfw.py 
> > --model_def nsfw_model/deploy.prototxt 
> > --pretrained_model nsfw_model/resnet_50_1by2_nsfw.caffemodel 
> > test_image.jpg
> > libdc1394 error: Failed to initialize libdc1394
> > Traceback (most recent call last):
> > File "./classify_nsfw.py", line 16, in 
> > import caffe
> > File "/opt/caffe/python/caffe/**init**.py", line 1, in 
> > from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
> > File "/opt/caffe/python/caffe/pycaffe.py", line 15, in 
> > import caffe.io
> > File "/opt/caffe/python/caffe/io.py", line 2, in 
> > import skimage.io
> > ImportError: No module named skimage.io
直接

pip install scikit-image

**Comment by jmjmjm123** [comment]
@qianjun1987    it helped ,thanks !

**Comment by Bech007** [comment]
hi 
how install skimage on centos 7
