### ISSUE TITLE
I have created a simple online demo

### ISSUE THREAD

**Issue by itoolset** [yahoo/open_nsfw#15]
Located at: http://itoolset.com/nsfw
So that people can try it online~

**Comment by kobe6672823** [comment]
really cool

**Comment by austingg** [comment]
great ! very convenient

**Comment by itoolset** [comment]
@kobe6672823 @austingg 
thanks all!

**Comment by jay-mahadeokar** [comment]
Thanks @itoolset.

**Comment by loretoparisi** [comment]
@itoolset amazing

**Comment by Jayhello** [comment]
why i can't visit it

**Comment by itoolset** [comment]
@Jayhello 
sorry, My vps has expired, feel free to fork my repo and rolling your own app, I will rebuild in a couple of days.
