### ISSUE TITLE
About the input size of the Image

### ISSUE THREAD

**Issue by chibai** [yahoo/open_nsfw#20]
This is a very stupid question.

I saw you resize the image to 256*256 in python script

but in line 6 of deploy.prototxt, input_param { shape: { dim: 1 dim: 3 dim: 224 dim: 224 } },
which means the input images should be 3 channels with size 224*224

so, what's the exactly right input size of the image?? 256 or 224??
Or I just misunderstood the python script and caffe structure??

**Comment by XuefeiW** [comment]
The script does this:
load an image;
resize image to 256x256 (line 64)
centre crop resized image to 224x224 (line 71)

So the input image of the model is  3x224x224

**Comment by jay-mahadeokar** [comment]
The resize to 256x256 and random crop to 224x224 is done during training for data augmentation. Refer the residual networks paper [section 3.4](https://arxiv.org/pdf/1512.03385v1.pdf). During runtime / test we take center crop after resize.
