### ISSUE TITLE
Why resize to (256, 256) ?

### ISSUE THREAD

**Issue by Mohanson** [yahoo/open_nsfw#25]
In deploy.prototxt, the input_param is `{ shape: { dim: 1 dim: 3 dim: 224 dim: 224 } }` but in classify_nsfw.py, images are resized to (256, 256).

**Comment by chibai** [comment]
@Mohanson  check the closed issue, i already asked the exactly same question.
In training phase, the image size is 256*256, then random crop size 224*224 to do data augmentation
While in test size, center cropping is uesd to test the image

In this situation, image are resized to 256*256, but caffe only process the center part 224*224

**Comment by Mohanson** [comment]
Very thanks and sorry for I didn't take a look in closed issues.
