### ISSUE TITLE
Does this project continue to be maintained?

### ISSUE THREAD

**Issue by willduan** [yahoo/open_nsfw#48]
I found that the graph is inactive since last november

**Comment by laowu8615** [comment]
remove standalone

**Comment by anish9** [comment]
that too didn't work

**Comment by laowu8615** [comment]
i try it again,it can be work with remove standalone

**Comment by gyehuda** [comment]
currently, @akappeler and @sachinfarfade are the maintainers on record. Please let me know if this changes and I'll update the team listing to reflect it.
