### ISSUE TITLE
Return NSFW score:   0.0

### ISSUE THREAD

**Issue by kharazi** [yahoo/open_nsfw#5]
Hi, Thanks for opensoucing(openmodeling!) this model.
I'm trying to test it for classify images but always, I got NSFW=0. It's seems somethings is wrong with my try.

[here](https://gist.github.com/kharazi/9ffaab7572072df53ec559b09c9ca328) you can see trace and it's same for any type of images

**Comment by jay-mahadeokar** [comment]
Can you check if you have the latest version of caffe installed?  Refer this [PR](https://github.com/yahoo/open_nsfw/pull/2) which adds docker support. We will review it soon and merge it so it has docker support, but if you try with that docker package / caffe version, I think it should work.

**Comment by kharazi** [comment]
Yes, I think I used from latest version of caffe(cloned from master branch of source code and compile, with `pycaffe='1.0.0-rc3'`). I'll test using this docker version.
