### ISSUE TITLE
System reboot when calling 'caffe_preprocess_and_compute'

### ISSUE THREAD

**Issue by LiberiFatali** [yahoo/open_nsfw#6]
My PC gets rebooted automatically. 

I notice that caffe model was loaded well, but it crashed at `scores = caffe_preprocess_and_compute(image_data, caffe_transformer=caffe_transformer, caffe_net=nsfw_net, output_layers=['prob'])`.

It still reboots when I switch to `caffe.set_mode_cpu()`.

Is there anything that I can do? Thank you.

**Comment by LiberiFatali** [comment]
I'm using latest source from caffe master repo.

**Comment by jay-mahadeokar** [comment]
Im not sure what your PC configurations are, but I suggest trying docker, we just added related documentation in Readme.

**Comment by LiberiFatali** [comment]
Switching to atlas (I was using openblas) solved this problem. I'm still not sure the cause.
Thanks.
