### ISSUE TITLE
Some images marked as nsfw are wrong

### ISSUE THREAD

**Issue by zhaoxy2850** [yahoo/open_nsfw#67]
Hi guys,
     I am using open_nsfw to classify images, but some images like the attachment(a avatar's wall, open_nsfw score:0.993217) is marked as nsfw. 
     Anyone knows how to solve this? Thank you very much!
![1523765279290](https://user-images.githubusercontent.com/1196476/38996397-af52d4b0-441d-11e8-9421-e4d9eaedde60.jpg)

**Comment by TheDailySpank** [comment]
I have used this model to score over 30,000,000 images and I can tell you that it will always say the grids of pictures have high scores. I am assuming it's because training set had nsfw video thumbnail contact sheets. You'll need to retrain it if you want to alter it's behavior.

**Comment by zhaoxy2850** [comment]
Thanks, I will train my own model instead.

**Comment by TechnikEmpire** [comment]
@zhaoxy2850 Training params are here:

https://github.com/jay-mahadeokar/pynetbuilder/tree/master/models/imagenet/resnet_50_1by2

**Comment by TechnikEmpire** [comment]
Alternatively you can write a segmentation algorithm to extract frames from input.

**Comment by zhaoxy2850** [comment]
@TechnikEmpire Thank you. ^_^
