### ISSUE TITLE
OpenNSFW with Docker

### ISSUE THREAD

**Issue by loretoparisi** [yahoo/open_nsfw#7]
I would like to share how to run NSFT with `docker`

1) Build a caffe docker image (GPU)

```
$ cd open_nsfw
$ wget https://raw.githubusercontent.com/BVLC/caffe/master/docker/standalone/gpu/Dockerfile
$ docker build -t caffe:cpu ./
```

To build for cpu only get the `Dockerfile` for cpu from `Caffe` repo

```
$ wget https://raw.githubusercontent.com/BVLC/caffe/master/docker/standalone/cpu/Dockerfile
```

2) When the image it's ready, we check `caffe` installation

```
$ docker run -ti caffe:cpu caffe --version
caffe version 1.0.0-rc3
```

3) We run bash in this folder as mapped volume with the option `--volume` in order to run the training manually

```
docker run -ti --volume=$(pwd):/workspace caffe:cpu bash
```

so we are in the docker `caffe` image

```
root@8855e6188183:/workspace#
```

4) Run `nsfw` in the current container volume

```
root@8855e6188183:/workspace#python ./classify_nsfw.py --model_def nsfw_model/deploy.prototxt --pretrained_model nsfw_model/resnet_50_1by2_nsfw.caffemodel anderson_210.jpg
```

and we are done

```
NSFW score:   0.14057905972
```

**Comment by jay-mahadeokar** [comment]
@loretoparisi thanks!  This looks great. There is already a [PR](https://github.com/yahoo/open_nsfw/pull/2) for running the nsfw model with docker. Can you take a look/review?

**Comment by loretoparisi** [comment]
@jay-mahadeokar I will, thanks.

**Comment by loretoparisi** [comment]
I have updated the PR thread with more info about running `open_nsfw` with `caffe:gpu` so with nvidia CUDA basically configuration. See https://github.com/yahoo/open_nsfw/pull/2

**Comment by Romamr1** [comment]
Hi guys
when i try to run: wget https://raw.githubusercontent.com/BVLC/caffe/master/docker/standalone/gpu/Dockerfile
I get an error: ERROR 404: Not Found.

Trying to follow the link also gives an error: 404

**Comment by loretoparisi** [comment]
@Romamr1 the file is https://github.com/BVLC/caffe/blob/master/docker/gpu/Dockerfile
