### ISSUE TITLE
I am also working on it in a startup company  for nsfw classify, you guys just ruin it 

### ISSUE THREAD

**Issue by terminats17** [yahoo/open_nsfw#9]
I will lost my job

**Comment by lcpandcode** [comment]
As a Chinese ,my English is not very good,I am so sorry I don't understand what you said.

**Comment by rsyring** [comment]
@terminats17 

> Code licensed under the BSD 2 clause license. See LICENSE file for terms.

They want you to use there code.  Use what they are doing to make your business better.
